# Generated by Django 5.0.6 on 2024-05-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='status',
            field=models.CharField(choices=[('proposed', 'Запланирована'), ('active', 'Активная'), ('resolved', 'На проверке'), ('closed', 'Закрытая')], default='proposed', max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('proposed', 'Запланирована'), ('active', 'Активная'), ('resolved', 'На проверке'), ('closed', 'Закрытая')], default='proposed', max_length=8),
        ),
    ]
